version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: video-processing:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - minio-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Воркер для скачивания видео
  download_worker:
    image: video-processing:latest
    command: celery -A app.worker worker --loglevel=info --queues=download_queue --concurrency=1
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - redis
      - app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - minio-network

  # Воркеры для обработки видео
  video_processing_worker:
    image: video-processing:latest
    command: celery -A app.worker worker --loglevel=info --queues=video_processing_queue --concurrency=2
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - redis
      - app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - minio-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis:alpine
    container_name: redis-queue
    ports:
      - "6379:6379"
    networks:
      - minio-network

networks:
  minio-network:
    driver: bridge

volumes:
  redis_data:
    name: redis_queue_data
    driver: local
