version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: video-processing:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./media:/app/media
      - ./results_step2.json:/app/results_step2.json
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - pg
      - redis
    networks:
      - minio-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Воркер для скачивания видео
  download_worker:
    image: video-processing:latest
    command: celery -A app.worker worker --loglevel=info --queues=download_queue --concurrency=1
    volumes:
      - .:/app
      - ./media:/app/media
      - ./results_step2.json:/app/results_step2.json
    depends_on:
      - redis
      - pg
      - app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - minio-network

  # Воркеры для обработки видео
  video_processing_worker:
    image: video-processing:latest
    command: celery -A app.worker worker --loglevel=info --queues=video_processing_queue --concurrency=2
    volumes:
      - .:/app
      - ./media:/app/media
      - ./results_step2.json:/app/results_step2.json
    depends_on:
      - redis
      - pg
      - app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - minio-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis:alpine
    container_name: redis-queue
    ports:
      - "6379:6379"
    networks:
      - minio-network

  pg:
    image: postgres
    environment:
      POSTGRES_DB: smart_house
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d smart_house" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - minio-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - minio-network
  

networks:
  minio-network:
    driver: bridge

volumes:
  redis_data:
    name: redis_queue_data
    driver: local
  pgdata:
