"""delete test

Revision ID: 03f110221ea1
Revises: f00cf28da732
Create Date: 2025-03-13 10:33:35.256265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f110221ea1'
down_revision: Union[str, None] = 'f00cf28da732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'link2')
    op.drop_column('videos', 'li12412')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('li12412', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('link2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
